Vstepanuga handle new match 1
leejr0/cs414-f19-001-Spaghetti-Coders pull request #118
Opened 2019-11-01 01:34 UTC by vstepanuga

Implemented the request for creating a new game with implemented database integration.

All previously written tests pass and the server ignites, however new functionality still remains to be tested.

2019-11-01 14:13 UTC, 3djeef approved these changes

2019-11-01 21:59 UTC, leejr0 requested changes
Some changes on the front-end are needed to make sure the board renders properly on the front-end.

2019-11-02 20:02 UTC, samstobbs approved these changes

2019-11-03 03:20 UTC, 3djeef requested changes
While it is not in this format, @leejr0 got a complete working demo up and running. Since we need to have the deliverables and our demo done and in our repository by 9 Monday morning, I think we should prioritize finishing deliverables and wait to implement these changes until the beginning of next sprint.

2019-11-03 18:29 UTC, closed without merging

2019-11-03 18:30 UTC, vstepanuga commented
I will be fixing this implementation in the next sprint iteration.